### ISSUE TITLE
Can't build project with 6.1.0 libs

### ISSUE THREAD

**Issue by Michael-Lazell** [enonic/lib-recaptcha#3]
I can't seem to build the project locally with 6.1.0 libs.

FAILURE: Build failed with an exception.
- What went wrong:
  Could not copy MANIFEST.MF to '/Users/mla/dev/sourcecode/lib-recaptcha/build/tmp/jar/MANIFEST.MF'.
  > No signature of method: aQute.bnd.osgi.Builder.setProperties() is applicable for argument types: (java.util.LinkedHashMap) values: [[-exportcontents:, Import-Package:_;resolution:=optional, Private-Package:site._;-split-package:=merge-first, ...]]
  Possible solutions: setProperties(java.io.File), setProperties(java.util.Properties), getProperties(), getProperties(), setProperties(java.io.File, java.io.File), addProperties(java.io.File)

It works just fine with 6.2.0 and above. I doubt anybody is still using 6.1.0. I suggest updating it on the next release.

**Comment by Bellfalasch** [comment]
This issue was forgotten about and now we don't support this old version of XP.
